INSERT INTO WOW_REWARDS.SEGMENTACIONES_WOW.SEGMENTACIONES
WITH 

RANGO_DE_FECHAS AS (
    -- Seleccionamos el rango de fechas para el cual queremos generar la segmentacion
    SELECT
        current_date() - 365 AS FECHA_INICIO_INACTIVOS,
        current_date() - 180 AS FECHA_INICIO_ACTIVOS,
        current_date() AS FECHA_FIN
),

VENTAS_ANY_BRAND AS (
    -- Filtramos solo las compras que sean validas
    SELECT
        *
    FROM
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_VENTAS_ORDENES_WOW
    WHERE
        POS_EMPLOYEE_ID NOT IN ('Power', '1 service cloud')
),

VENTAS_RESTAURANTES AS (
    SELECT
        CASE 
            WHEN MARCA IN ('ITS JUST WINGS','CHILIS MEXICO') THEN 'CHILIS'
            ELSE MARCA
        END AS BRAND,
        TRANSACTION_ID,
        VENTAS,
        EMAIL,
        to_date(DATETIME) AS FECHA
    FROM
        VENTAS_ANY_BRAND
    WHERE
        MARCA IN (
            'THE CHEESECAKE FACTORY MEXICO',
            'ITS JUST WINGS',
            'CHILIS MEXICO',
            'ITALIANNIS MEXICO',
            'P.F. CHANGS MEXICO',
            'VIPS MEXICO'
        )
),

PRIMERA_COMPRA_POR_MARCA AS (
    SELECT DISTINCT
        EMAIL,
        BRAND,
        min(FECHA) AS FECHA
    FROM
        VENTAS_RESTAURANTES
    GROUP BY
        EMAIL,
        BRAND
),

REGISTROS_TOTALES AS (
    SELECT
        EMAIL,
        min(to_date(TIMESTAMP)) AS FECHA_REGISTRO
    FROM
       SEGMENT_EVENTS.COREALSEA_PROD.REGISTRATION
    GROUP BY
        EMAIL
),

REGISTROS AS (
    SELECT
        REGISTROS_TOTALES.*,
        'REGISTROS' AS SEGMENTO,
        null AS MARCA
    FROM
        REGISTROS_TOTALES
    INNER JOIN
        RANGO_DE_FECHAS
    ON
        FECHA_REGISTRO < FECHA_INICIO_ACTIVOS
    LEFT JOIN
        VENTAS_ANY_BRAND
    USING(
        EMAIL
    )
    WHERE
        VENTAS_ANY_BRAND.EMAIL IS null
),

REGISTROS_SIN_COMPRA AS (
    SELECT
        REGISTROS_TOTALES.*,
        'REGISTROS_SIN_COMPRA' AS SEGMENTO,
        null AS MARCA
    FROM
        REGISTROS_TOTALES
    INNER JOIN
        RANGO_DE_FECHAS
    ON
        FECHA_REGISTRO BETWEEN FECHA_INICIO_ACTIVOS AND FECHA_FIN
    LEFT JOIN
        VENTAS_ANY_BRAND
    USING(
        EMAIL
    )
    WHERE
        VENTAS_ANY_BRAND.EMAIL IS null
),

NUEVOS_ACTIVOS AS (
    SELECT
        REGISTROS_TOTALES.*,
        'NUEVOS_ACTIVOS' AS SEGMENTO,
        'WOW' AS MARCA
    FROM
        REGISTROS_TOTALES
    INNER JOIN
        RANGO_DE_FECHAS
    ON
        FECHA_REGISTRO BETWEEN FECHA_INICIO_ACTIVOS AND FECHA_FIN
    LEFT JOIN
        VENTAS_RESTAURANTES
    ON
        lower(REGISTROS_TOTALES.EMAIL) = lower(VENTAS_RESTAURANTES.EMAIL)
    AND
        VENTAS_RESTAURANTES.FECHA BETWEEN FECHA_INICIO_ACTIVOS AND FECHA_FIN
    GROUP BY
        REGISTROS_TOTALES.EMAIL,
        FECHA_REGISTRO
    HAVING
        count(DISTINCT TRANSACTION_ID) = 1
),

VENTAS_ACTIVOS AS (
    SELECT
        'WOW' AS BRAND,
        EMAIL,
        COUNT(DISTINCT TRANSACTION_ID) AS ORD,
        SUM(VENTAS) AS VENTAS
    FROM
        VENTAS_RESTAURANTES
    JOIN
        RANGO_DE_FECHAS
    WHERE
        FECHA BETWEEN FECHA_INICIO_ACTIVOS AND FECHA_FIN
    AND
        EMAIL NOT IN (SELECT EMAIL FROM NUEVOS_ACTIVOS)
    GROUP BY
        EMAIL
),

ACTIVOS AS (
    SELECT
        EMAIL,
        ORD,
        BRAND AS MARCA,
        VENTAS AS SALES,
        VENTAS / ORD AS TICKET_PROMEDIO,
        percent_rank() OVER (
            PARTITION BY BRAND
            ORDER BY
                TICKET_PROMEDIO
        ) AS AOV_PERC,
        percent_rank() OVER (
            PARTITION BY BRAND
            ORDER BY
                ORD
        ) AS ORD_PERC,
        CASE
            WHEN AOV_PERC <= 0.25 THEN 'LOW'
            WHEN AOV_PERC <= 0.75 THEN 'AVG'
            ELSE 'HIGH'
        END AS SEGMENTO_MONETARY,
        CASE
            WHEN ORD_PERC <= 0.25 THEN 'LOW VALUE'
            WHEN ORD_PERC <= 0.75 THEN 'MEDIUM VALUE'
            ELSE 'HIGH VALUE'
        END AS SEGMENTO_FREQUENCY,
        SEGMENTO_FREQUENCY || '_' || SEGMENTO_MONETARY AS SEGMENTO_RFM,
        CASE
            WHEN SEGMENTO_RFM = 'HIGH VALUE_HIGH' THEN 'TOP VALUE'
            ELSE SEGMENTO_FREQUENCY
        END AS SEGMENTO
    FROM
        VENTAS_ACTIVOS
),

INACTIVOS_Y_PERDIDOS AS (
    SELECT
        'WOW' AS MARCA,
        EMAIL,
        max(FECHA) AS ULTIMA_VENTA,
        CASE
            WHEN ULTIMA_VENTA > FECHA_INICIO_INACTIVOS THEN 'INACTIVOS'
            ELSE 'PERDIDOS'
        END AS SEGMENTO
    FROM
        VENTAS_RESTAURANTES
    JOIN
        RANGO_DE_FECHAS
    GROUP BY
        EMAIL,
        FECHA_INICIO_INACTIVOS,
        FECHA_INICIO_ACTIVOS
    HAVING
        ULTIMA_VENTA < FECHA_INICIO_ACTIVOS
),

SEGMENTACION_TOTAL AS (
    SELECT
        EMAIL,
        SEGMENTO,
        MARCA
    FROM
        ACTIVOS

    UNION ALL

    SELECT
        EMAIL,
        SEGMENTO,
        MARCA
    FROM
        INACTIVOS_Y_PERDIDOS

    UNION ALL
    
    SELECT
        EMAIL,
        SEGMENTO,
        MARCA
    FROM
        NUEVOS_ACTIVOS

    UNION ALL
    
    SELECT
        EMAIL,
        SEGMENTO,
        MARCA
    FROM
        REGISTROS

    UNION ALL

    SELECT
        EMAIL,
        SEGMENTO,
        MARCA
    FROM
        REGISTROS_SIN_COMPRA
),

SEGMENTACION_GC AS (
    SELECT
        EMAIL,
        'CONTROL' AS FLAG_GC
    FROM
        SEGMENTACION_TOTAL tablesample bernoulli (10)
),

SEGMENTACION_GP_GC AS (
    SELECT
        EMAIL,
        ifnull(FLAG_GC, 'PROMOCION') AS GRUPO,
        SEGMENTO,
        MARCA
    FROM
        SEGMENTACION_TOTAL
    LEFT JOIN 
        SEGMENTACION_GC 
    USING(
        EMAIL
    )
),

INSTALLED_APP_ANDROID AS (
    SELECT
        USER_ID
    FROM
        SEGMENT_EVENTS.WOW_PROD_ANDROID.APPLICATION_OPENED
    INNER JOIN 
        RANGO_DE_FECHAS 
    ON
        to_date(TIMESTAMP) BETWEEN FECHA_INICIO_ACTIVOS AND FECHA_FIN
),

INSTALLED_APP_IOS AS (
    SELECT
        USER_ID
    FROM
        SEGMENT_EVENTS.WOW_PROD_IOS.APPLICATION_OPENED
    INNER JOIN 
        RANGO_DE_FECHAS 
    ON
        to_date(TIMESTAMP) BETWEEN FECHA_INICIO_ACTIVOS AND FECHA_FIN
),

INSTALLED_APP_TOTAL AS (
    SELECT * FROM INSTALLED_APP_IOS
    UNION ALL
    SELECT * FROM INSTALLED_APP_ANDROID
),

INSTALLED_APP_BY_USER AS (
    SELECT DISTINCT
        EMAIL
    FROM
        INSTALLED_APP_TOTAL
    INNER JOIN
        SEGMENT_EVENTS.SESSIONM_NEW.SM_USERS
    ON
        lower(INSTALLED_APP_TOTAL.USER_ID) = lower(SM_USERS.USER_ID)
),

CROSSBRAND_PRE_PIVOTED as(
    SELECT
        EMAIL,
        BRAND,
        ROW_NUMBER() OVER (PARTITION BY EMAIL ORDER BY min(FECHA) ASC) AS RN
    FROM
        VENTAS_RESTAURANTES
    GROUP BY
        EMAIL,
        BRAND
),

CROSSBRAND AS (
    SELECT
        EMAIL,
        *
    FROM
        CROSSBRAND_PRE_PIVOTED
    PIVOT(
        SUM(RN)
        FOR BRAND IN ('VIPS MEXICO','THE CHEESECAKE FACTORY MEXICO','CHILIS','ITALIANNIS MEXICO','P.F. CHANGS MEXICO')
    )AS PIVOTE
)

SELECT
    2023 AS ANIO,
    9 AS MES,
    SEGMENTACION_GP_GC.EMAIL,
    SEGMENTACION_GP_GC.GRUPO,
    SEGMENTACION_GP_GC.SEGMENTO,
    SEGMENTACION_GP_GC.MARCA,
    USUARIOS_SESSIONM.FIRST_NAME,
    USUARIOS_SESSIONM.LAST_NAME,
    CASE
        WHEN INSTALLED_APP_BY_USER.EMAIL IS NOT null THEN true
        ELSE false
    END AS APP_INSTALADA,
    ANIO || '_' || MES || '_' || MARCA || '_' || SEGMENTO || '_' || upper(APP_INSTALADA) AS ID_SEGMENTO,
    ifnull("'VIPS MEXICO'", 0) AS CROSSBRAND_VIPS_MEXICO,
    ifnull("'THE CHEESECAKE FACTORY MEXICO'", 0) AS CROSSBRAND_THE_CHEESECAKE_FACTORY_MEXICO,
    ifnull("'CHILIS'", 0) AS CROSSBRAND_CHILIS,
    ifnull("'ITALIANNIS MEXICO'", 0) AS CROSSBRAND_ITALIANNIS_MEXICO,
    ifnull("'P.F. CHANGS MEXICO'", 0) AS CROSSBRAND_PF_CHANGS_MEXICO
FROM
    SEGMENTACION_GP_GC
LEFT JOIN 
    WOW_REWARDS.WORK_SPACE_WOW_REWARDS.USUARIOS_SESSIONM
USING(
    EMAIL
)
LEFT JOIN 
    INSTALLED_APP_BY_USER 
USING(
    EMAIL
)
LEFT JOIN
    CROSSBRAND
USING(
    EMAIL
)
WHERE
    MARCA = 'WOW'
AND
    EMAIL NOT IN (
        'ccecercervcjcarlosdiazflres66@gmeil.comervacervabcervabtcervabtecervabtez'
    )
;

SELECT * FROM WOW_REWARDS.SEGMENTACIONES_WOW.SEGMENTACIONES LIMIT 100;