WITH

MESES AS (
    SELECT
        MES_ALSEA,
        ANIO_ALSEA,
        max(to_date(FECHA)) AS DOMINGO,
        DOMINGO - 180 AS FECHA_INICIO_MEDICION
    FROM
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    WHERE
    (
        ANIO_ALSEA = 2023
        AND
        MES_ALSEA <= 8
    )
    OR
    (
        ANIO_ALSEA = 2022
        AND
        MES_ALSEA >= 8
    )
    GROUP BY
        MES_ALSEA,
        ANIO_ALSEA
),

TRANSACCIONES_OLO AS (
    SELECT DISTINCT
        UPPER(MXP.EMAIL) AS EMAIL,
        to_date(OLO.ORDER_DATE) AS FECHA
    FROM
       "SEGMENT_EVENTS"."DOMINOS_OLO"."MXPOWERSALESLOG" MXP
    INNER JOIN 
        "SEGMENT_EVENTS"."DOMINOS_OLO"."DPMSALES_FULL" OLO
    ON 
        OLO.ORDER_NUMBER = MXP.ORDERNUMBER AND OLO.LOCATION_CODE = MXP.STORENUMBER 
    AND 
        TO_CHAR(OLO.ORDER_DATE,'YYYY-MM-DD') = MXP.ORDERDATE
    WHERE 
        OLO.ORDER_STATUS_CODE = 4
    AND 
        OLO.LOCATION_CODE NOT IN ('13001' , '13006', '13021', '11000')
    AND 
        UPPER(OLO.SOURCE_CODE) IN ('ANDROID' , 'DESKTOP', 'IOS', 'MOBILE', 'WEB', 'ANDROID2', 'DESKTOP2', 'IOSAPP', 'MOBILE2', 'WHATSAPP')
),

TRANSACCIONES_CLOUD AS (
    SELECT DISTINCT 
        upper(A.EMAIL) AS EMAIL,
        to_date(SUBSTRING(A.STOREORDERID,1,10)) AS FECHA
    FROM 
        "SEGMENT_EVENTS"."DOMINOS_GOLO"."VENTA_CLOUD" A
    WHERE 
        A.STOREID NOT LIKE '9%'
    AND 
        A.SOURCEORGANIZATIONURI IN ('order.dominos.com','resp-order.dominos.com','iphone.dominos.mx','android.dominos.mx') 
    AND 
        A.SOURCEORGANIZATIONURI IS NOT NULL
),

TRANSACCIONES_TOTAL AS (
    SELECT * FROM TRANSACCIONES_CLOUD
    UNION ALL
    SELECT * FROM TRANSACCIONES_OLO
)

SELECT
    ANIO_ALSEA,
    MES_ALSEA,
    DOMINGO AS FECHA_FIN_MEDICION,
    FECHA_INICIO_MEDICION,
    count(DISTINCT EMAIL)
FROM
    TRANSACCIONES_TOTAL
INNER JOIN
    MESES
ON
    FECHA BETWEEN FECHA_INICIO_MEDICION AND DOMINGO
GROUP BY
    MES_ALSEA,
    ANIO_ALSEA,
    DOMINGO,
    FECHA_INICIO_MEDICION
ORDER BY
    ANIO_ALSEA DESC,
    MES_ALSEA DESC
;