SELECT DISTINCT
    EMAIL
FROM
    SEGMENT_EVENTS.SESSIONM_SBX.FACT_TRANSACTIONS
INNER JOIN
    WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
ON
    to_date(CREATED_AT) = FECHA
WHERE
    ANIO_ALSEA = 2023
AND
    MES_ALSEA = 7
;