WITH

MESES AS (
    SELECT
        MES_ALSEA,
        ANIO_ALSEA,
        max(to_date(FECHA)) AS DOMINGO,
        DOMINGO - 90 AS FECHA_INICIO_MEDICION
    FROM
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    WHERE
        ANIO_ALSEA >= 2022
    GROUP BY
        MES_ALSEA,
        ANIO_ALSEA
)

SELECT
    ANIO_ALSEA,
    MES_ALSEA,
    (sum(CHECK_AMOUNT) / 1.16) / count(DISTINCT TRANSACTION_ID) AS TICKET_PROMEDIO,
    count(DISTINCT TRANSACTION_ID) / count(DISTINCT EMAIL) AS FRECUENCIA,
    (sum(CHECK_AMOUNT) / 1.16)/ count(DISTINCT EMAIL) AS CLV
FROM
    SEGMENT_EVENTS.SESSIONM_SBX.FACT_TRANSACTIONS
INNER JOIN
    MESES
ON
    to_date(CREATED_AT) <= DOMINGO
AND
    FECHA_INICIO_MEDICION <= to_date(CREATED_AT)
GROUP BY
    ANIO_ALSEA,
    MES_ALSEA
ORDER BY
    ANIO_ALSEA,
    MES_ALSEA
;
