WITH
CTE AS (
    SELECT
        CASE
            WHEN SM_TRANSACTION_DISCOUNTS.NAME LIKE 'Beb o Pan Gold%' THEN 'Beb o Pan Gold'
            WHEN SM_TRANSACTION_DISCOUNTS.NAME LIKE 'Beb Cumple%' THEN 'Beb Cumple'
            ELSE SM_TRANSACTION_DISCOUNTS.NAME
        END AS PROMO,
        split_part(SM_TRANSACTION_ITEMS.POS_ITEM_KEY, '_', 2) AS SKUU,
        count(*) AS CANTIDAD
    FROM
        "SEGMENT_EVENTS"."SESSIONM_SBX"."SM_TRANSACTION_HEADERS" TXN
    INNER JOIN
        "SEGMENT_EVENTS"."SESSIONM_SBX"."SM_TRANSACTION_ITEMS"
    ON
        SM_TRANSACTION_ITEMS.TRANSACTION_ID = TXN.TRANSACTION_ID
    INNER JOIN
        "SEGMENT_EVENTS"."SESSIONM_SBX"."SM_MASTER_ITEMS" MITEM
    ON
        SM_TRANSACTION_ITEMS.MASTER_ITEM_ID = MITEM.ITEM_ID
    INNER JOIN 
    (
        SELECT DISTINCT TRANSACTION_ID, USER_ID
        FROM 
            "SEGMENT_EVENTS"."SESSIONM_SBX"."SM_TRANSACTION_PAYMENTS"
    ) PAY
    ON
        TXN.TRANSACTION_ID =PAY.TRANSACTION_ID
    INNER JOIN
        "SEGMENT_EVENTS"."SESSIONM_SBX"."SM_TRANSACTION_DISCOUNTS"
    ON
        SM_TRANSACTION_DISCOUNTS.TRANSACTION_ID = TXN.TRANSACTION_ID
    INNER JOIN
        "WOW_REWARDS"."WORK_SPACE_WOW_REWARDS"."DS_DIM_TIME" T
    ON
        T.FECHA = TO_DATE(TXN.CREATED_AT)
    WHERE
        T.FECHA <= to_date('2023-09-26')
    AND
        (to_date('2023-09-26') - 90) >= T.FECHA
    AND
        PROMO IN ('Beb o Pan Gold', 'Beb Cumple')
    GROUP BY 
        PROMO,
        SKUU
    ORDER BY 
        CANTIDAD DESC
)

SELECT
    CTE.*,
    min(DISPLAY_NAME) AS NOMBRE
FROM
    CTE
INNER JOIN
    SEGMENT_EVENTS.SESSIONM_SBX.SM_MASTER_ITEMS
ON
    SM_MASTER_ITEMS.SKU LIKE SKUU || '%'
GROUP BY
    PROMO,
    SKUU,
    CANTIDAD
;