WITH

REGISTROS_LOYALTY AS (
    SELECT
        lower(EMAIL) AS EMAIL,
        to_date(JOING_DATE, 'dd/mm/yy HH24:MI:SS.FF') AS FECHA
    FROM
        "SEGMENT_EVENTS"."STARBUCKS_REWARDS_MX"."ALSE_LOY_MEMBER_ALL" M
    INNER JOIN
        SEGMENT_EVENTS.STARBUCKS_REWARDS_MX.ALSE_LOY_PERSON_ALL AS PERSONS
    ON
        M.ID_PERSON = PERSONS.ID
),

REGISTROS_SESSIONM AS (
    SELECT
        lower(EMAIL) AS EMAIL,
        to_date(CREATED_AT) AS FECHA
    FROM
        SEGMENT_EVENTS.SESSIONM_SBX.SM_USERS
),

REGISTROS_TOTALES AS (
    SELECT
        EMAIL,
        min(FECHA) AS FECHA_REGISTRO
    FROM
    (
        SELECT * FROM REGISTROS_LOYALTY
        UNION ALL
        SELECT * FROM REGISTROS_SESSIONM
    )
    GROUP BY
        EMAIL
)

SELECT
    ANIO_ALSEA,
    MES_ALSEA,
    count(EMAIL)
FROM
    REGISTROS_TOTALES
INNER JOIN
    WOW_REWARDS.work_space_wow_rewards.DS_DIM_TIME
ON
    FECHA = FECHA_REGISTRO
GROUP BY
    ANIO_ALSEA,
    MES_ALSEA
ORDER BY
    ANIO_ALSEA DESC,
    MES_ALSEA DESC
;