WITH

SBX_TOTAL_ALSEA AS (
    SELECT
        TOT.TIENDA,
        SUM(TOT.VENTAS) VENTAS_SBX,
        SUM(TOT.ORDENES) ORDENES_SBX,
        ANIO_ALSEA,
        MES_ALSEA,
        SEM_ALSEA
    FROM 
        "WOW_REWARDS"."WORK_SPACE_WOW_REWARDS"."DATOS_TOTAL_ALSEA" TOT
    INNER JOIN 
        "WOW_REWARDS"."WORK_SPACE_WOW_REWARDS"."DS_DIM_TIME" T
    ON 
        T.FECHA = to_date(TOT.FECHA,'DD/MM/YYYY')
    AND 
        MARCA ='STARBUCKS COFFEE MEXICO'
    GROUP BY 
        TOT.TIENDA,
        ANIO_ALSEA,
        MES_ALSEA,
        SEM_ALSEA
),

LOYALTY AS (
   SELECT 
        B.BRANCH AS TIENDA,
        B.BRANCH_NAME AS SUCURSAL_NOMBRE,
        (SUM(VO.AMOUNT)/1.16) AS VENTA,
        COUNT(DISTINCT VO.TICKET_NUMBER) AS ORDENES,
        ANIO_ALSEA,
        MES_ALSEA,
        SEM_ALSEA
    FROM 
        "SEGMENT_EVENTS"."STARBUCKS_REWARDS_MX"."ALSE_LOY_TRANSACTION_ALL" VO
    INNER JOIN 
        "SEGMENT_EVENTS"."STARBUCKS_REWARDS_MX"."ALSE_LOY_BRANCH_ALL" B
    ON 
        VO.BRANCH = B.ID 
    INNER JOIN
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    ON
        to_date(VO.TRANSACTION_DATE, 'dd/mm/yy HH24:MI:SS') = FECHA
    WHERE  
        1 = 1
    AND 
        VO.PRODUCT_ID = 100000002457617 --TOTAL DE TICKET
    AND 
        VO.PROCESSING_SUB_STATUS IN ('ORA_TXN_SUB_STAT_SUCCESS','ORA_TXN_SUB_STAT_NO_PROMO_QF') --TRANSACCIONES EXITOSAS
    AND 
        VO.STATUS IN ('ORA_TXN_STAT_PROCESSED') 
    AND 
        VO.TRANSACTION_TYPE = ('ORA_TXN_ACC')
    AND 
        VO.BRANCH NOT IN ('100000002450436','100000002452968') --ESAS TIENDAS SON DE PRUEBA
    AND 
        VO.PART_SEARCH NOT IN ('Migracion Saldos') -- DIFERENCIAS DE SALDO POR MIGRACIÒN DE MY STARBUCKS REWARDS A STARBUCKS REWARDS
    AND 
        VO.TICKET_NUMBER NOT LIKE 'TCKFALLA%' -- FALLA DE SISTEMA
    GROUP BY 
        B.BRANCH,
        B.BRANCH_NAME,
        ANIO_ALSEA,
        MES_ALSEA,
        SEM_ALSEA
),

SESSIONM AS (
    SELECT   
        SUM(TXN.CHECK_AMOUNT / 1.16) AS VENTA,
        COUNT(DISTINCT TXN.TRANSACTION_ID) AS ORDENES,
        CASE 
            WHEN SUBSTR(STORES.NAME,-6,5) = '(8957' THEN '38957' 
            ELSE SUBSTR(STORES.NAME,-6,5)
        END AS TIENDA,
        ANIO_ALSEA,
        MES_ALSEA,
        SEM_ALSEA
    FROM 
        "SEGMENT_EVENTS"."SESSIONM_SBX"."SM_TRANSACTION_HEADERS" TXN
    INNER JOIN 
        "SEGMENT_EVENTS"."SESSIONM_SBX"."SM_RETAILER_STORES" STORES
    ON 
        TXN.RETAILER_STORE_ID = STORES.RETAILER_STORE_ID
    INNER JOIN
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    ON
        to_date(CREATED_AT) = FECHA
    WHERE 
        CHANNEL <> 'API' and TXN.TRANSACTION_ID not in (
            select distinct 
                TRANSACTION_ID 
            from 
                SEGMENT_EVENTS.SESSIONM_SBX.SM_TRANSACTION_ITEMS 
            where 
                POS_ITEM_KEY IN ('MEXLEG_106_sbx', 'MEXLEG_109_sbx')
    )
    GROUP BY
        TIENDA,
        ANIO_ALSEA,
        MES_ALSEA,
        SEM_ALSEA
),

SR_TOTAL AS (
    SELECT upper(trim(TIENDA)) AS TIENDA, VENTA, ORDENES, SEM_ALSEA, MES_ALSEA, ANIO_ALSEA FROM LOYALTY
    UNION ALL
    SELECT upper(trim(TIENDA)) AS TIENDA, VENTA, ORDENES, SEM_ALSEA, MES_ALSEA, ANIO_ALSEA FROM SESSIONM
),

SR AS (
    SELECT
        TIENDA,
        ANIO_ALSEA,
        MES_ALSEA,
        SEM_ALSEA,
        sum(VENTA) AS VENTAS_SR,
        sum(ORDENES) AS ORDENES_SR
    FROM
        SR_TOTAL
    GROUP BY
        TIENDA,
        SEM_ALSEA,
        MES_ALSEA,
        ANIO_ALSEA
)

SELECT
    TIENDA,
    CC_NOMBRE,
    sum(VENTAS_SR) / sum(VENTAS_SBX) AS TENDER,
    sum(VENTAS_SR) AS VENTA_SR,
    ANIO_ALSEA,
    MES_ALSEA,
    SEM_ALSEA
FROM
    SR
LEFT JOIN
    SBX_TOTAL_ALSEA
USING(
    TIENDA,
    SEM_ALSEA,
    MES_ALSEA,
    ANIO_ALSEA
)
LEFT JOIN
     SEGMENT_EVENTS.SESSIONM_SBX.SBX_DIRECTORIO
ON
    to_char(CC) = TIENDA
WHERE
    ANIO_ALSEA = 2022
AND
    34 <= SEM_ALSEA
AND
    44 <= SEM_ALSEA
GROUP BY
    TIENDA,
    CC_NOMBRE,
    ANIO_ALSEA,
    MES_ALSEA,
    SEM_ALSEA
ORDER BY
    ANIO_ALSEA DESC,
    SEM_ALSEA DESC,
    TENDER
;