WITH

INTERVALO_FECHAS AS (
    SELECT
        to_date('2023-05-29') AS FECHA_INICIO,
        to_date('2023-08-27') AS FECHA_FIN
),

TRANSACCIONES_BY_USER AS (
    SELECT
        EMAIL,
        sum(CHECK_AMOUNT / 1.16) AS VENTAS,
        count(DISTINCT TRANSACTION_ID) AS FREQ,
        VENTAS / FREQ AS AOV
    FROM
        SEGMENT_EVENTS.SESSIONM_SBX.FACT_TRANSACTIONS
    INNER JOIN
        INTERVALO_FECHAS
    ON
        FECHA_INICIO <= to_date(CREATED_AT)
    AND 
        to_date(CREATED_AT) <= FECHA_FIN
    WHERE
        EMAIL IS NOT null
    GROUP BY
        EMAIL
),

SEGMENTACION_BASE_ACTIVOS AS (
    SELECT 
        TRANSACCIONES_BY_USER.*,
        CASE
            WHEN FREQ <= PERCENTILE_CONT(0.20) WITHIN GROUP (ORDER BY FREQ) OVER () THEN 'LIGHT'
            WHEN FREQ <= PERCENTILE_CONT(0.40) WITHIN GROUP (ORDER BY FREQ) OVER () THEN 'MIDL'
            WHEN FREQ <= PERCENTILE_CONT(0.60) WITHIN GROUP (ORDER BY FREQ) OVER () THEN 'MIDH'
            WHEN FREQ <= PERCENTILE_CONT(0.80) WITHIN GROUP (ORDER BY FREQ) OVER () THEN 'HEAVY'
            ELSE 'SUPER'
        END AS SEGMENTO,
        CASE
            WHEN AOV <= ROUND(PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY AOV) OVER ()) THEN 'LOW'
            WHEN AOV <= ROUND(PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY AOV) OVER ()) THEN 'AVG'
            ELSE 'HIGH'
        END AS TAG_GRUPO,
        SEGMENTO || '_' || TAG_GRUPO AS FULL_SEGMENTO,
        CASE
            WHEN FULL_SEGMENTO IN ('LIGHT_LOW', 'LIGHT_AVG', 'LIGHT_HIGH', 'MIDL_LOW', 'MIDL_AVG', 'MIDH_LOW') THEN 'LOW'
            WHEN FULL_SEGMENTO IN ('MIDL_HIGH', 'MIDH_AVG', 'MIDH_HIGH', 'HEAVY_LOW', 'HEAVY_AVG') THEN 'MEDIUM' 
            WHEN FULL_SEGMENTO IN ('HEAVY_HIGH', 'SUPER_LOW', 'SUPER_AVG') THEN 'HIGH'
            ELSE 'TOP'
        END AS ULTRASEGMENTO
    FROM
        TRANSACCIONES_BY_USER
),

DIAS_RECOMPRA AS (
    SELECT DISTINCT
        EMAIL,
        nth_value(to_date(CREATED_AT), 1) OVER (PARTITION BY EMAIL ORDER BY to_date(CREATED_AT)) AS FECHA_PRIMERA_VENTA,
        nth_value(to_date(CREATED_AT), 2) OVER (PARTITION BY EMAIL ORDER BY to_date(CREATED_AT)) AS FECHA_SEGUNDA_VENTA,
        FECHA_SEGUNDA_VENTA - FECHA_PRIMERA_VENTA AS DIAS_RECOMPRA
    FROM
        SEGMENT_EVENTS.SESSIONM_SBX.FACT_TRANSACTIONS
    INNER JOIN
        INTERVALO_FECHAS
    WHERE
        FECHA_INICIO <= to_date(CREATED_AT)
    AND
        to_date(CREATED_AT) <= FECHA_FIN
    QUALIFY
        FECHA_SEGUNDA_VENTA IS NOT null
)

SELECT
    -- ULTRASEGMENTO,
    avg(DIAS_RECOMPRA)
FROM
    DIAS_RECOMPRA
INNER JOIN
    SEGMENTACION_BASE_ACTIVOS
USING(
    EMAIL
)
-- GROUP BY
    -- ULTRASEGMENTO
;