WITH
PRE_PIVOT AS (
    SELECT
        RETAILER_STORE_ID,
        STORE_NAME,
        CHANNEL,
        count(DISTINCT TRANSACTION_ID) AS TRANSACCIONES
    FROM
        SEGMENT_EVENTS.SESSIONM_SBX.FACT_TRANSACTIONS
    WHERE
        SOURCE = 'SESSIONM_SBX'
    GROUP BY
        RETAILER_STORE_ID,
        STORE_NAME,
        CHANNEL
)

SELECT
    *
FROM
    PRE_PIVOT 
    PIVOT (sum(TRANSACCIONES) FOR CHANNEL IN ('POS', 'Pick up', 'Delivery', 'Car Pick up'))
    AS TABLA (CECO, NOMBRE, ORDENES_POS, ORDENES_PICKUP, ORDENES_DELIVERY, ORDENES_CAR_PICKUP)
;
-- Distinct Store name: 782
-- Distinct Retailer store ID : 783
-- Distinct both: 783

SELECT
    count(DISTINCT RETAILER_STORE_ID),
    count(DISTINCT STORE_NAME),
    CHANNEL
FROM
    SEGMENT_EVENTS.SESSIONM_SBX.FACT_TRANSACTIONS
WHERE
    SOURCE = 'SESSIONM_SBX'
GROUP BY
    CHANNEL
;
