WITH

CATALOGO_SUCURSALES AS (
    SELECT DISTINCT
        CC AS RETAILER_STORE_ID,
        REGION,
        CASE
            WHEN ESTADO LIKE '%Baja California' THEN 'Baja California'
            WHEN ESTADO LIKE '%Baja California Sur' THEN 'Baja California Sur'
            WHEN ESTADO LIKE '%Chihuahua' THEN 'Chihuahua'
            WHEN ESTADO LIKE '%Jalisco' THEN 'Jalisco'
            WHEN ESTADO LIKE '%Nayarit' THEN 'Nayarit'
            WHEN ESTADO LIKE '%Sinaloa' THEN 'Sinaloa'
            WHEN ESTADO LIKE '%Sonora' THEN 'Sonora'
            ELSE ESTADO
        END AS ESTADO,
        CASE
            WHEN CIUDAD LIKE 'Quer%' THEN 'Queretaro'
            WHEN CIUDAD LIKE 'Tlanepantla' THEN 'Tlalnepantla'
            WHEN CIUDAD LIKE 'Tuxla Gutierrez' THEN 'Tuxtla Gutierrez'
            ELSE CIUDAD
        END AS CIUDAD,
        CC_NOMBRE,
        DM
    FROM
        SEGMENT_EVENTS.SESSIONM_SBX.SBX_DIRECTORIO
),

TRANSACCIONES AS (
    SELECT
        to_date(CREATED_AT) AS FECHA,
        CASE
            WHEN RETAILER_STORE_ID = 8957 THEN 38957
            ELSE RETAILER_STORE_ID
        END AS RETAILER_STORE_ID,
        CHECK_AMOUNT
    FROM
        SEGMENT_EVENTS.SESSIONM_SBX.FACT_TRANSACTIONS
),

TOTAL_ALSEA_POR_CIUDAD_Y_SEMANA AS (
    SELECT
        T.SEM_ALSEA,
        CATALOGO_SUCURSALES.REGION,
        CATALOGO_SUCURSALES.ESTADO,
        CATALOGO_SUCURSALES.CIUDAD,
        CATALOGO_SUCURSALES.RETAILER_STORE_ID,
        CATALOGO_SUCURSALES.CC_NOMBRE,
        SUM(TOT.VENTAS) VENTA_TOTAL
    FROM 
        "WOW_REWARDS"."WORK_SPACE_WOW_REWARDS"."DATOS_TOTAL_ALSEA" TOT
    INNER JOIN 
        "WOW_REWARDS"."WORK_SPACE_WOW_REWARDS"."DS_DIM_TIME" T
    ON 
        T.FECHA = TO_CHAR(TO_DATE(TOT.FECHA,'DD/MM/YYYY'),'YYYY-MM-DD')
    AND 
        T.ANIO_ALSEA = 2023    ---ADECUAR EL AÑO QUE SE NECESITE
    AND 
        MARCA = 'STARBUCKS COFFEE MEXICO'
    INNER JOIN
        CATALOGO_SUCURSALES
    ON
        TOT.TIENDA = CATALOGO_SUCURSALES.RETAILER_STORE_ID
    GROUP BY 
        T.ANIO_ALSEA,
        T.SEM_ALSEA,
        CATALOGO_SUCURSALES.REGION,
        CATALOGO_SUCURSALES.ESTADO,
        CATALOGO_SUCURSALES.CIUDAD,
        CATALOGO_SUCURSALES.RETAILER_STORE_ID,
        CATALOGO_SUCURSALES.CC_NOMBRE,
        CATALOGO_SUCURSALES.DM
),

VENTA_SR_POR_CIUDAD_Y_SEMANA AS (
    SELECT
        DS_DIM_TIME.SEM_ALSEA,
        CATALOGO_SUCURSALES.REGION,
        CATALOGO_SUCURSALES.ESTADO,
        CATALOGO_SUCURSALES.CIUDAD,
        CATALOGO_SUCURSALES.RETAILER_STORE_ID,
        CATALOGO_SUCURSALES.CC_NOMBRE,
        CATALOGO_SUCURSALES.DM,
        sum(TRANSACCIONES.CHECK_AMOUNT) / 1.16 AS VENTA_SR
    FROM
        TRANSACCIONES
    LEFT JOIN
        CATALOGO_SUCURSALES
    USING(
        RETAILER_STORE_ID
    )
    INNER JOIN
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    USING(
        FECHA
    )
    WHERE
        ANIO_ALSEA = 2023
    GROUP BY
        DS_DIM_TIME.ANIO_ALSEA,
        DS_DIM_TIME.SEM_ALSEA,
        CATALOGO_SUCURSALES.REGION,
        CATALOGO_SUCURSALES.ESTADO,
        CATALOGO_SUCURSALES.CIUDAD,
        CATALOGO_SUCURSALES.RETAILER_STORE_ID,
        CATALOGO_SUCURSALES.CC_NOMBRE,
        CATALOGO_SUCURSALES.DM
),

PRE_PIVOT AS (
    SELECT
        SEM_ALSEA,
        REGION,
        ESTADO,
        CIUDAD,
        RETAILER_STORE_ID,
        CC_NOMBRE,
        DM, 
        VENTA_SR
    FROM
        TOTAL_ALSEA_POR_CIUDAD_Y_SEMANA
    INNER JOIN
        VENTA_SR_POR_CIUDAD_Y_SEMANA
    USING(
        SEM_ALSEA,
        REGION,
        ESTADO,
        CIUDAD,
        RETAILER_STORE_ID,
        CC_NOMBRE
    )
)

SELECT 
    *
FROM 
    PRE_PIVOT
PIVOT (
    sum(VENTA_SR)
    FOR SEM_ALSEA IN (
        1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
        11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29,30
  )
)
;