WITH

RANGO_DE_FECHAS AS (
    SELECT
        to_date('2023-07-30') AS FECHA_FIN,
        FECHA_FIN - 365 AS FECHA_INICIO
)

SELECT
    count(DISTINCT EMAIL) AS ACTIVOS_SBX
FROM
    SEGMENT_EVENTS.SESSIONM_SBX.FACT_TRANSACTIONS
INNER JOIN
    RANGO_DE_FECHAS
ON
    to_date(CREATED_AT) <= FECHA_FIN
AND
    FECHA_INICIO < to_date(CREATED_AT)