WITH

TRIMESTRES AS (
    SELECT
        ANIO_ALSEA,
        CASE
            WHEN MES_ALSEA IN (1,2,3) THEN 'Q1'
            WHEN MES_ALSEA IN (4,5,6) THEN 'Q2'
            WHEN MES_ALSEA IN (7,8,9) THEN 'Q3'
            WHEN MES_ALSEA IN (10,11,12) THEN 'Q4'
        END AS TRIMESTRE,
        max(to_date(FECHA)) AS FECHA_FIN,
        FECHA_FIN - 90 AS FECHA_INICIO
    FROM
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    WHERE
        ANIO_ALSEA IN (2021, 2022, 2023)
    GROUP BY
        TRIMESTRE,
        ANIO_ALSEA
)

SELECT
    ANIO_ALSEA,
    TRIMESTRE,
    count(DISTINCT lower(EMAIL))
FROM
    SEGMENT_EVENTS.SESSIONM_SBX.FACT_TRANSACTIONS
INNER JOIN
    TRIMESTRES
ON
    to_date(CREATED_AT) <= FECHA_FIN
AND 
    FECHA_INICIO <= to_date(CREATED_AT)
GROUP BY
    TRIMESTRE,
    ANIO_ALSEA
ORDER BY
    ANIO_ALSEA,
    TRIMESTRE
;