WITH

PERIODO_ACTUAL AS (
    SELECT
        to_date(max(FECHA)) AS FECHA_FIN,
        FECHA_FIN - 180 AS FECHA_INICIO,
        ANIO_ALSEA,
        MES_ALSEA,
        SEM_ALSEA
    FROM
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    WHERE
        ANIO_ALSEA = 2023
    AND
        SEM_ALSEA = 30
    GROUP BY
        ANIO_ALSEA,
        MES_ALSEA,
        SEM_ALSEA
),

SEMANA_PREVIA AS (
    SELECT
        to_date(max(FECHA)) AS FECHA_FIN,
        FECHA_FIN - 180 AS FECHA_INICIO
    FROM
    (
        SELECT
            CASE WHEN SEM_ALSEA = 1 THEN ANIO_ALSEA - 1 ELSE ANIO_ALSEA END AS ANIO_ALSEA,
            CASE WHEN SEM_ALSEA = 1 THEN 52             ELSE SEM_ALSEA - 1 END AS SEM_ALSEA
        FROM
            PERIODO_ACTUAL
    )
    INNER JOIN
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    USING(
        ANIO_ALSEA,
        SEM_ALSEA
    )
),

MES_PREVIO AS (
    SELECT
        to_date(max(FECHA)) AS FECHA_FIN,
        FECHA_FIN - 180 AS FECHA_INICIO
    FROM
    (
        SELECT
            CASE WHEN MES_ALSEA = 1 THEN ANIO_ALSEA - 1 ELSE ANIO_ALSEA END AS ANIO_ALSEA,
            CASE WHEN MES_ALSEA = 1 THEN 12             ELSE MES_ALSEA - 1 END AS MES_ALSEA
        FROM
            PERIODO_ACTUAL
    )
    INNER JOIN
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    USING(
        ANIO_ALSEA,
        MES_ALSEA
    )
),

ANIO_PREVIO AS (
    SELECT
        to_date(max(FECHA)) AS FECHA_FIN,
        FECHA_FIN - 180 AS FECHA_INICIO
    FROM
    (
        SELECT
            ANIO_ALSEA - 1 AS ANIO_ALSEA
        FROM
            PERIODO_ACTUAL
    )
    INNER JOIN
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    USING(
        ANIO_ALSEA
    )
),

APP_INSTALLS AS (
    SELECT to_date(TIMESTAMP) AS FECHA FROM SEGMENT_EVENTS.GOLO_ANDROID_PROD.APPLICATION_INSTALLED
    UNION ALL
    SELECT to_date(TIMESTAMP) AS FECHA FROM SEGMENT_EVENTS.GOLO_IOS_PROD.APPLICATION_INSTALLED
    UNION ALL
    SELECT to_date(TIMESTAMP) AS FECHA FROM SEGMENT_EVENTS.DOMINOS_ANDROID_APP_PRODUCCION.APPLICATION_INSTALLED
    UNION ALL
    SELECT to_date(TIMESTAMP) AS FECHA FROM SEGMENT_EVENTS.DOMINOS_APP_PRODUCCION.APPLICATION_INSTALLED
),

APP_INSTALLS_PERIODO_ACTUAL AS (
    SELECT
        count(*) AS APP_INSTALLS
    FROM
        APP_INSTALLS
    INNER JOIN
        PERIODO_ACTUAL
    ON
        FECHA BETWEEN FECHA_INICIO AND FECHA_FIN
),

APP_INSTALLS_SEMANA_PREVIA AS (
    SELECT
        count(*) AS APP_INSTALLS
    FROM
        APP_INSTALLS
    INNER JOIN
        SEMANA_PREVIA
    ON
        FECHA BETWEEN FECHA_INICIO AND FECHA_FIN
),

APP_INSTALLS_MES_PREVIO AS (
    SELECT
        count(*) AS APP_INSTALLS
    FROM
        APP_INSTALLS
    INNER JOIN
        MES_PREVIO
    ON
        FECHA BETWEEN FECHA_INICIO AND FECHA_FIN
),

APP_INSTALLS_ANIO_PREVIO AS (
    SELECT
        count(*) AS APP_INSTALLS
    FROM
        APP_INSTALLS
    INNER JOIN
        ANIO_PREVIO
    ON
        FECHA BETWEEN FECHA_INICIO AND FECHA_FIN
)

SELECT
    APP_INSTALLS_PERIODO_ACTUAL.APP_INSTALLS AS APP_INSTALLS_PERIODO_ACTUAL,

    APP_INSTALLS_SEMANA_PREVIA.APP_INSTALLS AS APP_INSTALLS_SEMANA_PREVIA,
    APP_INSTALLS_PERIODO_ACTUAL / APP_INSTALLS_SEMANA_PREVIA AS PERCENT_V_SEMANA_PREVIA,

    APP_INSTALLS_MES_PREVIO.APP_INSTALLS AS APP_INSTALLS_MES_PREVIO,
    APP_INSTALLS_PERIODO_ACTUAL / APP_INSTALLS_MES_PREVIO AS PERCENT_V_MES_PREVIO,

    APP_INSTALLS_ANIO_PREVIO.APP_INSTALLS AS APP_INSTALLS_ANIO_PREVIO,
    APP_INSTALLS_PERIODO_ACTUAL / APP_INSTALLS_ANIO_PREVIO AS PERCENT_V_ANIO_PREVIO
FROM
    APP_INSTALLS_PERIODO_ACTUAL
INNER JOIN
    APP_INSTALLS_SEMANA_PREVIA
INNER JOIN
    APP_INSTALLS_MES_PREVIO
INNER JOIN
    APP_INSTALLS_ANIO_PREVIO
;