WITH

MESES AS (
    SELECT
        ANIO_ALSEA,
        MES_ALSEA,
        to_date(max(FECHA)) AS FECHA_FIN,
        -- to_date(min(FECHA)) AS FECHA_INICIO
        FECHA_FIN - 180 AS FECHA_INICIO
    FROM
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    WHERE
    -- (
    --     ANIO_ALSEA = 2022
    --     AND
    --     MES_ALSEA >= 8
    -- )
    -- OR
    (
        ANIO_ALSEA = 2022
        AND
        MES_ALSEA = 8
    )
    GROUP BY
        ANIO_ALSEA,
        MES_ALSEA
),

TRANSACCIONES_OLO AS (
    SELECT DISTINCT
        lower(EMAIL) AS EMAIL,
        to_date(MXP.ORDERDATE) AS FECHA,
        SUM(OLO.ORDERFINALPRICE / 1.16) AS VENTAS
    FROM
       "SEGMENT_EVENTS"."DOMINOS_OLO"."MXPOWERSALESLOG" MXP
    INNER JOIN 
        "SEGMENT_EVENTS"."DOMINOS_OLO"."DPMSALES_FULL" OLO
    ON 
        OLO.ORDER_NUMBER = MXP.ORDERNUMBER AND OLO.LOCATION_CODE = MXP.STORENUMBER 
    AND 
        TO_CHAR(OLO.ORDER_DATE,'YYYY-MM-DD') = MXP.ORDERDATE
    WHERE 
        OLO.ORDER_STATUS_CODE = 4
    AND 
        OLO.LOCATION_CODE NOT IN ('13001' , '13006', '13021', '11000')
    AND 
        UPPER(OLO.SOURCE_CODE) IN ('ANDROID' , 'DESKTOP', 'IOS', 'MOBILE', 'WEB', 'ANDROID2', 'DESKTOP2', 'IOSAPP', 'MOBILE2', 'WHATSAPP')
    GROUP BY
        EMAIL,
        FECHA
),

TRANSACCIONES_CLOUD AS (
    SELECT DISTINCT 
        lower(A.EMAIL) AS EMAIL,
        to_date(SUBSTRING(A.STOREORDERID,1,10)) AS FECHA,
        sum(PAYMENTSAMOUNT / 1.16) AS VENTAS
    FROM 
        "SEGMENT_EVENTS"."DOMINOS_GOLO"."VENTA_CLOUD" A
    WHERE 
        A.STOREID NOT LIKE '9%'
    AND 
        A.SOURCEORGANIZATIONURI IN ('order.dominos.com','resp-order.dominos.com','iphone.dominos.mx','android.dominos.mx') 
    AND 
        A.SOURCEORGANIZATIONURI IS NOT NULL
    GROUP BY
        EMAIL,
        FECHA 
)

SELECT
    ANIO_ALSEA,
    MES_ALSEA,
    sum(VENTAS) / count(DISTINCT EMAIL) AS CLV
FROM
(
    SELECT * FROM TRANSACCIONES_OLO
    UNION ALL
    SELECT * FROM TRANSACCIONES_CLOUD
)
INNER JOIN
    MESES
ON
    FECHA BETWEEN FECHA_INICIO AND FECHA_FIN
GROUP BY
    ANIO_ALSEA,
    MES_ALSEA
ORDER BY
    ANIO_ALSEA DESC,
    MES_ALSEA DESC
;
