WITH

INTERVALO_FECHAS AS (
    SELECT
        to_date('2023-04-03') AS FECHA_INICIO,
        to_date('2023-07-02') AS FECHA_FIN
),


VENTAS_OLO AS (
    SELECT 
        FECHA,
        EMAIL,
        SUM(OLO.ORDERFINALPRICE / 1.16) VENTAS,
        COUNT(DISTINCT TO_CHAR(ORDER_DATE,'YYYY-MM-DD')||LOCATION_CODE||OLO.ORDER_NUMBER) FREQ
    FROM
        "SEGMENT_EVENTS"."DOMINOS_OLO"."DPMSALES_FULL" OLO
    INNER JOIN 
        "WOW_REWARDS"."WORK_SPACE_WOW_REWARDS"."DS_DIM_TIME" T 
    ON 
        T.FECHA = TO_CHAR(OLO.ORDER_DATE, 'YYYY-MM-DD')
    INNER JOIN
        "SEGMENT_EVENTS"."DOMINOS_OLO"."MXPOWERSALESLOG" MXP 
    ON 
        OLO.ORDER_NUMBER = MXP.ORDERNUMBER 
    AND 
        OLO.LOCATION_CODE = MXP.STORENUMBER 
    AND
        TO_CHAR(OLO.ORDER_DATE,'YYYY-MM-DD') = MXP.ORDERDATE
    WHERE 
        UPPER(SOURCE_CODE)  IN ('ANDROID2','DESKTOP2','IOSAPP','DESKTOP','MOBILE2','ANDROID')
    GROUP BY
        FECHA,
        EMAIL
),

VENTAS_CLOUD AS (
    SELECT 
        FECHA,
        EMAIL,
        SUM(A.PAYMENTSAMOUNT/1.16) AS VENTAS,
        COUNT(DISTINCT to_char(FECHA) || A.STOREID ||A.StoreOrderID) AS FREQ
    FROM 
        "SEGMENT_EVENTS"."DOMINOS_GOLO"."VENTA_CLOUD" A
    INNER JOIN 
        "WOW_REWARDS"."WORK_SPACE_WOW_REWARDS"."DS_DIM_TIME" T  
    ON 
        SUBSTRING(A.STOREORDERID,1,10) = T.FECHA
    WHERE 
        A.STOREID NOT LIKE '9%'
    GROUP BY
        FECHA,
        EMAIL
),

VENTA_TOTAL AS (
    SELECT
        *
    FROM
    (
        SELECT * FROM VENTAS_OLO
        UNION ALL
        SELECT * FROM VENTAS_CLOUD
    )
    INNER JOIN
        INTERVALO_FECHAS
    ON
        FECHA BETWEEN FECHA_INICIO AND FECHA_FIN
)

SELECT
    count(DISTINCT EMAIL) AS CUSTOMERS,
    sum(VENTAS) AS TOTAL_SALES,
    ratio_to_report(TOTAL_SALES) OVER () AS PERCENT_SALES,
    sum(FREQ) AS ORDENES,
    ORDENES / CUSTOMERS AS FREQUENCY,
    TOTAL_SALES / ORDENES AS AVERAGE_TICKET,
    TOTAL_SALES / CUSTOMERS AS CLV
FROM
    VENTA_TOTAL