WITH

ALL_INSTALLS AS (
    SELECT to_date(TIMESTAMP) AS FECHA FROM SEGMENT_EVENTS.GOLO_ANDROID_PROD.APPLICATION_INSTALLED
    UNION ALL
    SELECT to_date(TIMESTAMP) AS FECHA FROM SEGMENT_EVENTS.GOLO_IOS_PROD.APPLICATION_INSTALLED
    UNION ALL
    SELECT to_date(TIMESTAMP) AS FECHA FROM SEGMENT_EVENTS.DOMINOS_ANDROID_APP_PRODUCCION.APPLICATION_INSTALLED
    UNION ALL
    SELECT to_date(TIMESTAMP) AS FECHA FROM SEGMENT_EVENTS.DOMINOS_APP_PRODUCCION.APPLICATION_INSTALLED
),

SEMANA_ACTUAL AS (
    SELECT
        count(*) AS SEMANA_ACTUAL
    FROM
        ALL_INSTALLS
    INNER JOIN
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    USING(
        FECHA
    )
    WHERE
        ANIO_ALSEA = 2023
    AND
        SEM_ALSEA = 35
    ORDER BY
        FECHA DESC
),

SEMANA_PREVIA AS (
    SELECT
        count(*) AS SEMANA_PREVIA
    FROM
        ALL_INSTALLS
    INNER JOIN
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    USING(
        FECHA
    )
    WHERE
        ANIO_ALSEA = 2023
    AND
        SEM_ALSEA = 34
    ORDER BY
        FECHA DESC
),

SEMANAL AS (
    SELECT
        *,
        (SEMANA_ACTUAL - SEMANA_PREVIA) / SEMANA_PREVIA AS PERCENT_V_SEMANA_PREVIA
    FROM
        SEMANA_ACTUAL
    JOIN
        SEMANA_PREVIA
),

MES_ACTUAL AS (
    SELECT
        count(*) AS MES_ACTUAL
    FROM
        ALL_INSTALLS
    INNER JOIN
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    USING(
        FECHA
    )
    WHERE
        ANIO_ALSEA = 2023
    AND
        MES_ALSEA = 9
    AND
        SEM_ALSEA <= 35
    ORDER BY
        FECHA DESC
),

MES_PREVIO AS (
    SELECT
        count(*) AS MES_PREVIO
    FROM
        ALL_INSTALLS
    INNER JOIN
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    USING(
        FECHA
    )
    WHERE
        ANIO_ALSEA = 2023
    AND
        MES_ALSEA = 8
    ORDER BY
        FECHA DESC
),

MENSUAL AS (
    SELECT
        *,
        (MES_ACTUAL - MES_PREVIO) / MES_PREVIO AS PERCENT_V_MES_PREVIO
    FROM
        MES_ACTUAL
    JOIN
        MES_PREVIO
),

ANIO_ACTUAL AS (
    SELECT
        count(*) AS ANIO_ACTUAL
    FROM
        ALL_INSTALLS
    INNER JOIN
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    USING(
        FECHA
    )
    WHERE
        ANIO_ALSEA = 2023
    AND
        SEM_ALSEA <= 35
    ORDER BY
        FECHA DESC
),

ANIO_PREVIO AS (
    SELECT
        count(*) AS ANIO_PREVIO
    FROM
        ALL_INSTALLS
    INNER JOIN
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    USING(
        FECHA
    )
    WHERE
        ANIO_ALSEA = 2022
    AND
        SEM_ALSEA <= 35
    ORDER BY
        FECHA DESC
),

ANUAL AS (
    SELECT
        *,
        (ANIO_ACTUAL - ANIO_PREVIO) / ANIO_PREVIO AS PERCENT_V_ANIO_PREVIO
    FROM
        ANIO_ACTUAL
    JOIN
        ANIO_PREVIO
)

SELECT
    *
FROM
    SEMANAL
JOIN
    MENSUAL
JOIN
    ANUAL