WITH

INTERVALO_FECHAS AS (
    SELECT
        to_date('2023-04-03') AS FECHA_INICIO,
        to_date('2023-07-02') AS FECHA_FIN
),

ALL_INSTALLS AS (
    SELECT to_date(TIMESTAMP) AS FECHA FROM SEGMENT_EVENTS.GOLO_ANDROID_PROD.APPLICATION_INSTALLED
    UNION ALL
    SELECT to_date(TIMESTAMP) AS FECHA FROM SEGMENT_EVENTS.GOLO_IOS_PROD.APPLICATION_INSTALLED
    UNION ALL
    SELECT to_date(TIMESTAMP) AS FECHA FROM SEGMENT_EVENTS.DOMINOS_ANDROID_APP_PRODUCCION.APPLICATION_INSTALLED
    UNION ALL
    SELECT to_date(TIMESTAMP) AS FECHA FROM SEGMENT_EVENTS.DOMINOS_APP_PRODUCCION.APPLICATION_INSTALLED
)

SELECT
    count(*) AS INSTALACIONES
FROM
    ALL_INSTALLS
INNER JOIN
   INTERVALO_FECHAS
ON
    FECHA BETWEEN FECHA_INICIO AND FECHA_FIN