SELECT
    ANIO_ALSEA,
    MES_ALSEA,
    SERVICEMETHOD,
    sum(OLO.ORDERFINALPRICE) / 1.16 AS VENTA,
    ratio_to_report(VENTA) OVER (PARTITION BY ANIO_ALSEA, MES_ALSEA) PARTICIPACION_A_TOTAL_OLO
FROM
    "SEGMENT_EVENTS"."DOMINOS_OLO"."MXPOWERSALESLOG" MXP
INNER JOIN 
    "SEGMENT_EVENTS"."DOMINOS_OLO"."DPMSALES_FULL" OLO
ON 
    OLO.ORDER_NUMBER = MXP.ORDERNUMBER AND OLO.LOCATION_CODE = MXP.STORENUMBER 
AND 
    TO_CHAR(OLO.ORDER_DATE,'YYYY-MM-DD') = MXP.ORDERDATE
INNER JOIN
    WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
ON
    OLO.ORDER_DATE = FECHA
WHERE 
    OLO.ORDER_STATUS_CODE = 4
AND 
    OLO.LOCATION_CODE NOT IN ('13001' , '13006', '13021', '11000')
AND 
    UPPER(OLO.SOURCE_CODE) IN ('ANDROID' , 'DESKTOP', 'IOS', 'MOBILE', 'WEB', 'ANDROID2', 'DESKTOP2', 'IOSAPP', 'MOBILE2', 'WHATSAPP')
GROUP BY
    SERVICEMETHOD,
    ANIO_ALSEA,
    MES_ALSEA
ORDER BY
    ANIO_ALSEA DESC,
    MES_ALSEA DESC