WITH

INTERVALO_FECHAS AS (
    SELECT
        to_date('2023-04-03') AS FECHA_INICIO,
        to_date('2023-07-02') AS FECHA_FIN
),


TRANSACCIONES_OLO AS (
    SELECT DISTINCT
        lower(MXP.EMAIL) AS EMAIL,
        to_date(OLO.ORDER_DATE) AS FECHA
    FROM
       "SEGMENT_EVENTS"."DOMINOS_OLO"."MXPOWERSALESLOG" MXP
    INNER JOIN 
        "SEGMENT_EVENTS"."DOMINOS_OLO"."DPMSALES_FULL" OLO
    ON 
        OLO.ORDER_NUMBER = MXP.ORDERNUMBER AND OLO.LOCATION_CODE = MXP.STORENUMBER 
    AND 
        TO_CHAR(OLO.ORDER_DATE,'YYYY-MM-DD') = MXP.ORDERDATE
    WHERE 
        OLO.ORDER_STATUS_CODE = 4
    AND 
        OLO.LOCATION_CODE NOT IN ('13001' , '13006', '13021', '11000')
    AND 
        UPPER(OLO.SOURCE_CODE) IN ('ANDROID' , 'DESKTOP', 'IOS', 'MOBILE', 'WEB', 'ANDROID2', 'DESKTOP2', 'IOSAPP', 'MOBILE2', 'WHATSAPP')
),

TRANSACCIONES_CLOUD AS (
    SELECT DISTINCT 
        lower(A.EMAIL) AS EMAIL,
        to_date(SUBSTRING(A.STOREORDERID,1,10)) AS FECHA
    FROM 
        "SEGMENT_EVENTS"."DOMINOS_GOLO"."VENTA_CLOUD" A
    WHERE 
        A.STOREID NOT LIKE '9%'
    AND 
        A.SOURCEORGANIZATIONURI IN ('order.dominos.com','resp-order.dominos.com','iphone.dominos.mx','android.dominos.mx') 
    AND 
        A.SOURCEORGANIZATIONURI IS NOT NULL
),

TRANSACCIONES_TOTAL AS (
    SELECT * FROM TRANSACCIONES_CLOUD
    UNION ALL
    SELECT * FROM TRANSACCIONES_OLO
),

PRIMERAS_COMPRAS_BY_USER AS (
    SELECT
        EMAIL,
        min(FECHA) AS FECHA
    FROM
        TRANSACCIONES_TOTAL
    GROUP BY
        EMAIL
)

SELECT
    count(DISTINCT EMAIL) AS PRIMERAS_COMPRAS
FROM
    PRIMERAS_COMPRAS_BY_USER
INNER JOIN
    INTERVALO_FECHAS
ON
    FECHA BETWEEN FECHA_INICIO AND FECHA_FIN
;
WITH

TRANSACCIONES_OLO AS (
    SELECT DISTINCT
        lower(MXP.EMAIL) AS EMAIL,
        to_date(OLO.ORDER_DATE) AS FECHA
    FROM
       "SEGMENT_EVENTS"."DOMINOS_OLO"."MXPOWERSALESLOG" MXP
    INNER JOIN 
        "SEGMENT_EVENTS"."DOMINOS_OLO"."DPMSALES_FULL" OLO
    ON 
        OLO.ORDER_NUMBER = MXP.ORDERNUMBER AND OLO.LOCATION_CODE = MXP.STORENUMBER 
    AND 
        TO_CHAR(OLO.ORDER_DATE,'YYYY-MM-DD') = MXP.ORDERDATE
    WHERE 
        OLO.ORDER_STATUS_CODE = 4
    AND 
        OLO.LOCATION_CODE NOT IN ('13001' , '13006', '13021', '11000')
    AND 
        UPPER(OLO.SOURCE_CODE) IN ('ANDROID' , 'DESKTOP', 'IOS', 'MOBILE', 'WEB', 'ANDROID2', 'DESKTOP2', 'IOSAPP', 'MOBILE2', 'WHATSAPP')
),

TRANSACCIONES_CLOUD AS (
    SELECT DISTINCT 
        lower(A.EMAIL) AS EMAIL,
        to_date(SUBSTRING(A.STOREORDERID,1,10)) AS FECHA
    FROM 
        "SEGMENT_EVENTS"."DOMINOS_GOLO"."VENTA_CLOUD" A
    WHERE 
        A.STOREID NOT LIKE '9%'
    AND 
        A.SOURCEORGANIZATIONURI IN ('order.dominos.com','resp-order.dominos.com','iphone.dominos.mx','android.dominos.mx') 
    AND 
        A.SOURCEORGANIZATIONURI IS NOT NULL
),

TRANSACCIONES_TOTAL AS (
    SELECT * FROM TRANSACCIONES_CLOUD
    UNION ALL
    SELECT * FROM TRANSACCIONES_OLO
),

PRIMERAS_COMPRAS_BY_USER AS (
    SELECT
        EMAIL,
        min(FECHA) AS FECHA
    FROM
        TRANSACCIONES_TOTAL
    GROUP BY
        EMAIL
),

SEMANA_ACTUAL AS (
    SELECT
        count(DISTINCT EMAIL) AS SEMANA_ACTUAL
    FROM
        PRIMERAS_COMPRAS_BY_USER
    INNER JOIN
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    USING(
        FECHA
    )
    WHERE
        ANIO_ALSEA = 2023
    AND
        SEM_ALSEA = 35
),

SEMANA_PREVIA AS (
    SELECT
        count(DISTINCT EMAIL) AS SEMANA_PREVIA
    FROM
        PRIMERAS_COMPRAS_BY_USER
    INNER JOIN
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    USING(
        FECHA
    )
    WHERE
        ANIO_ALSEA = 2023
    AND
        SEM_ALSEA = 34
),

SEMANAL AS (
    SELECT
        *,
        (SEMANA_ACTUAL - SEMANA_PREVIA) / SEMANA_PREVIA AS PERCENT_V_SEMANA_PREVIA
    FROM
        SEMANA_ACTUAL
    JOIN
        SEMANA_PREVIA
),

MES_ACTUAL AS (
    SELECT
        count(DISTINCT EMAIL) AS MES_ACTUAL
    FROM
        PRIMERAS_COMPRAS_BY_USER
    INNER JOIN
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    USING(
        FECHA
    )
    WHERE
        ANIO_ALSEA = 2023
    AND
        MES_ALSEA = 9
    AND
        SEM_ALSEA <= 35
),

MES_PREVIO AS (
    SELECT
        count(DISTINCT EMAIL) AS MES_PREVIO
    FROM
        PRIMERAS_COMPRAS_BY_USER
    INNER JOIN
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    USING(
        FECHA
    )
    WHERE
        ANIO_ALSEA = 2023
    AND
        MES_ALSEA = 8
),

MENSUAL AS (
    SELECT
        *,
        (MES_ACTUAL - MES_PREVIO) / MES_PREVIO AS PERCENT_V_MES_PREVIO
    FROM
        MES_ACTUAL
    JOIN
        MES_PREVIO
),

ANIO_ACTUAL AS (
    SELECT
        count(DISTINCT EMAIL) AS ANIO_ACTUAL
    FROM
        PRIMERAS_COMPRAS_BY_USER
    INNER JOIN
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    USING(
        FECHA
    )
    WHERE
        ANIO_ALSEA = 2023
    AND
        SEM_ALSEA <= 35
),

ANIO_PREVIO AS (
    SELECT
        count(DISTINCT EMAIL) AS ANIO_PREVIO
    FROM
        PRIMERAS_COMPRAS_BY_USER
    INNER JOIN
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    USING(
        FECHA
    )
    WHERE
        ANIO_ALSEA = 2022
    AND
        SEM_ALSEA <= 35
),

ANUAL AS (
    SELECT
        *,
        (ANIO_ACTUAL - ANIO_PREVIO) / ANIO_PREVIO AS PERCENT_V_ANIO_PREVIO
    FROM
        ANIO_ACTUAL
    JOIN
        ANIO_PREVIO
)

SELECT
    *
FROM
    SEMANAL
JOIN
    MENSUAL
JOIN
    ANUAL
;