SELECT 
    A.LLAVE, 
    A.TIPO_CUPON,
    VTA.SOURCE_SALES,
    TO_CHAR(VTA.FDIDDIA,'DD-MM-YYYY'),
    VTA.FCIDTIENDA,
    VTA.FIIDCLIENTE, 
    VTA.FIIDCLASGRAL1,
    VTA.FNIMPSUBTOTAL,
    VTA.FNIMPGRANTOT,
    VTA.PHONE, 
    T.ANIO_ALSEA,
    T.MES_ALSEA,
    T.SEM_ALSEA
FROM 
(
    SELECT DISTINCT
        (TO_CHAR(FDIDDIA,'YYYYMMDD')||'-'||FCIDTIENDA||'-'||FITICKET) AS LLAVE,
        CASE
            WHEN FCIDDESCUENTO IN (4493,4494) THEN 'ADQUISICION'
            ELSE 'RECUPERACION'
        END AS TIPO_CUPON  
    FROM
        SEGMENT_EVENTS.ALOPERACIONES.TAFDESCUENTOSORDENES3
    WHERE
        FCIDDESCUENTO in (4493,4494,4501)
) AS A
INNER JOIN
    "SEGMENT_EVENTS"."DOMINOS_POS"."FACT_DOMINOS_SALES" VTA
ON
    A.LLAVE = VTA.CUSTOM_ORDER_ID
INNER JOIN 
    "WOW_REWARDS"."WORK_SPACE_WOW_REWARDS"."DS_DIM_TIME" AS T
ON 
    T.FECHA = TO_CHAR(VTA.FDIDDIA, 'YYYY-MM-DD')
;    
SELECT DISTINCT
    (TO_CHAR(FDIDDIA,'YYYYMMDD')||'-'||FCIDTIENDA||'-'||FITICKET) AS LLAVE,
    CASE
        WHEN FCIDDESCUENTO IN (4493,4494) THEN 'ADQUISICION'
        ELSE 'RECUPERACION'
    END AS TIPO_CUPON  
FROM
    SEGMENT_EVENTS.ALOPERACIONES.TAFDESCUENTOSORDENES3
WHERE
    FCIDDESCUENTO in (4493,4494,4501)