WITH 

ENVIADOS AS (
    SELECT
        FOLIO_CUPON,
        USER_ID,
        to_date(max(TIMESTAMP)) AS FECHA,
        STEP
    FROM
        SEGMENT_EVENTS.HTTP_REGISTRA_CUPON.COUPON_RECORD AS ENVIADOS
    WHERE
        SOURCE = 'SBX Journey Nuevos'
    GROUP BY
        FOLIO_CUPON,
        USER_ID,
        STEP
    HAVING
        FECHA >= to_date('2023-07-10')
)

SELECT
    ANIO_ALSEA,
    SEM_ALSEA,
    count(REDIMIDOS.MONTO_VENTA) AS REDENCIONES,
    sum(REDIMIDOS.MONTO_VENTA) / 1.16 AS VENTA_CON_REDENCION
FROM
    ENVIADOS 
LEFT JOIN
    SEGMENT_EVENTS.CUPONERA_ALSEA_PROD.REDEMPTION_COUPON AS REDIMIDOS
ON
    ENVIADOS.FOLIO_CUPON = REDIMIDOS.ID_COUPON
INNER JOIN
    WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
ON
    to_date(REDIMIDOS.TIMESTAMP) = DS_DIM_TIME.FECHA
GROUP BY
    ANIO_ALSEA,
    SEM_ALSEA
ORDER BY
    ANIO_ALSEA DESC,
    SEM_ALSEA DESC
;