WITH

NOSR AS (
    SELECT DISTINCT 
        PROGRAM_WELCOMING.EMAIL,
        to_date(dateadd(hour, -5, PROGRAM_WELCOMING.UUID_TS)) AS CREATED
    FROM 
        SEGMENT_EVENTS.PERSONAS_STARBUCKS_PERSONAS.IDENTIFIES
    INNER JOIN 
        SEGMENT_EVENTS.COREALSEASBX_PROD.PROGRAM_WELCOMING 
    ON
        lower(PROGRAM_WELCOMING.EMAIL) = lower(IDENTIFIES.USER_ID)
    WHERE 
        IDENTIFIES.CONTEXT_PERSONAS_COMPUTATION_KEY LIKE ('j_o_sbx_02_neowifi_v_%')
),

PRIMERA_VENTA AS (
    SELECT DISTINCT
        EMAIL,
        first_value(CHECK_AMOUNT / 1.16) OVER (PARTITION BY EMAIL ORDER BY TRANSACTION_DATE) AS VENTAS,
        first_value(TRANSACTION_DATE)    OVER (PARTITION BY EMAIL ORDER BY TRANSACTION_DATE) AS FECHA
    FROM 
        "SEGMENT_EVENTS"."SESSIONM_SBX"."SM_TRANSACTION_HEADERS" TXN
    INNER JOIN 
    (
        SELECT DISTINCT 
            TRANSACTION_ID, 
            USER_ID
        FROM 
            "SEGMENT_EVENTS"."SESSIONM_SBX"."SM_TRANSACTION_PAYMENTS"
    ) AS Q
    USING(
        TRANSACTION_ID
    )
    INNER JOIN
        SEGMENT_EVENTS.SESSIONM_SBX.SM_USERS
    USING(
        USER_ID
    )
    WHERE 
        TXN.CHANNEL<> 'API'
    AND
        TXN.TRANSACTION_ID NOT IN 
        (
            SELECT DISTINCT  
                TRANSACTION_ID 
            FROM 
                SEGMENT_EVENTS.SESSIONM_SBX.SM_TRANSACTION_ITEMS
            WHERE 
                POS_ITEM_KEY IN (
                    'MEXLEG_106_sbx',
                    'MEXLEG_109_sbx'
                ) 
        )
)

SELECT 
    ANIO_ALSEA,
    SEM_ALSEA,
    count(DISTINCT PRIMERA_VENTA.EMAIL) AS USR_PRIMERA_VENTA,
    sum(PRIMERA_VENTA.VENTAS) AS VENTAS
FROM 
    NOSR
INNER JOIN
    PRIMERA_VENTA
ON
    lower(NOSR.EMAIL) = lower(PRIMERA_VENTA.EMAIL)
INNER JOIN
    WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME AS TIME
ON 
    to_date(PRIMERA_VENTA.FECHA) = TIME.FECHA
GROUP BY
    ANIO_ALSEA,
    SEM_ALSEA
ORDER BY 
    ANIO_ALSEA DESC,
    SEM_ALSEA DESC
;