WITH 

VENTAS_ANY_BRAND AS (
    -- Filtramos solo las compras que sean validas
    SELECT
        *
    FROM
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_VENTAS_ORDENES_WOW
    WHERE
        POS_EMPLOYEE_ID NOT IN ('Power', '1 service cloud')
),

REGISTROS_TOTALES AS (
    SELECT
        lower(EMAIL) AS EMAIL,
        min(to_date(TIMESTAMP)) AS FECHA_REGISTRO
    FROM
       SEGMENT_EVENTS.COREALSEA_PROD.REGISTRATION
    GROUP BY
        lower(EMAIL)
)

SELECT
    ANIO_ALSEA,
    REGISTROS_TOTALES.EMAIL,
    USUARIOS_SESSIONM.FIRST_NAME,
    USUARIOS_SESSIONM.LAST_NAME
FROM
    REGISTROS_TOTALES
INNER JOIN
    WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
ON
    FECHA = FECHA_REGISTRO
LEFT JOIN
    VENTAS_ANY_BRAND
ON
    lower(VENTAS_ANY_BRAND.EMAIL) = lower(REGISTROS_TOTALES.EMAIL)
LEFT JOIN 
    WOW_REWARDS.WORK_SPACE_WOW_REWARDS.USUARIOS_SESSIONM
ON
    lower(REGISTROS_TOTALES.EMAIL) = lower(USUARIOS_SESSIONM.EMAIL)
WHERE
    VENTAS_ANY_BRAND.EMAIL IS null
AND
    ANIO_ALSEA = 2023
;