WITH

VENTAS_RESTAURANTES AS (
    SELECT DISTINCT
        CASE 
            WHEN MARCA IN ('ITS JUST WINGS','CHILIS MEXICO') THEN 'CHILIS'
            ELSE MARCA
        END AS BRAND,
        EMAIL,
        ANIO_ALSEA,
        MES_ALSEA,
        count(DISTINCT TRANSACTION_ID) AS TRANSACCIONES
    FROM
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_VENTAS_ORDENES_WOW
    INNER JOIN
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    ON
        FECHA = to_date(DATETIME)
    WHERE
        POS_EMPLOYEE_ID NOT IN ('Power', '1 service cloud')
    AND
        ANIO_ALSEA = 2023
    GROUP BY
        EMAIL,
        ANIO_ALSEA,
        MES_ALSEA,
        BRAND
),

CLIENTES_POR_RESTAURANTE AS (
    SELECT DISTINCT
        EMAIL,
        ANIO_ALSEA,
        MES_ALSEA,
        BRAND AS MARCA,
        TRANSACCIONES,
        CASE 
            WHEN count(DISTINCT BRAND) OVER (PARTITION BY EMAIL, ANIO_ALSEA, MES_ALSEA) = 1 THEN 'UNIMARCA'
            ELSE 'CROSS'
        END AS UNICOS_OR_CROSS
    FROM
        VENTAS_RESTAURANTES
),

SELECT
    ANIO_ALSEA,
    MES_ALSEA,
    MARCA,
    sum(CASE WHEN UNICOS_OR_CROSS = 'UNIMARCA' THEN 1 ELSE 0 END) AS CLIENTES_UNICOS,
    sum(CASE WHEN UNICOS_OR_CROSS = 'CROSS' THEN 1 ELSE 0 END) AS CLIENTES_CROSS,
    sum(TRANSACCIONES) AS TOTAL_TRANSACCIONES
FROM
    CLIENTES_POR_RESTAURANTE
GROUP BY
    ANIO_ALSEA,
    MES_ALSEA,
    MARCA
ORDER BY
    ANIO_ALSEA,
    MES_ALSEA,
    MARCA
;
WITH

RANGO_DE_FECHAS AS (
    SELECT
        ANIO_ALSEA,
        MES_ALSEA,
        to_date(max(FECHA)) - 365 AS FECHA_INICIO_INACTIVOS,
        to_date(max(FECHA)) - 180 AS FECHA_INICIO_ACTIVOS,
        to_date(max(FECHA)) AS FECHA_FIN
    FROM
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    WHERE
        ANIO_ALSEA = 2023
    GROUP BY
        ANIO_ALSEA,
        MES_ALSEA
),

INSTALLED_APP_ANDROID AS (
    SELECT
        ANIO_ALSEA,
        MES_ALSEA,
        USER_ID
    FROM
        SEGMENT_EVENTS.WOW_PROD_ANDROID.APPLICATION_OPENED
    INNER JOIN 
        RANGO_DE_FECHAS 
    ON
        to_date(TIMESTAMP) BETWEEN FECHA_INICIO_ACTIVOS AND FECHA_FIN
),

INSTALLED_APP_IOS AS (
    SELECT
        ANIO_ALSEA,
        MES_ALSEA,
        USER_ID
    FROM
        SEGMENT_EVENTS.WOW_PROD_IOS.APPLICATION_OPENED
    INNER JOIN 
        RANGO_DE_FECHAS 
    ON
        to_date(TIMESTAMP) BETWEEN FECHA_INICIO_ACTIVOS AND FECHA_FIN
),

INSTALLED_APP_TOTAL AS (
    SELECT * FROM INSTALLED_APP_IOS
    UNION ALL
    SELECT * FROM INSTALLED_APP_ANDROID
)

SELECT
    ANIO_ALSEA,
    MES_ALSEA,
    count(DISTINCT USER_ID) AS USUARIOS_CON_APP_INSTALADA
FROM
    INSTALLED_APP_TOTAL
GROUP BY
    ANIO_ALSEA,
    MES_ALSEA
ORDER BY
    ANIO_ALSEA DESC,
    MES_ALSEA DESC
;

WITH

INSTALLED_APP_ANDROID AS (
    SELECT
        ANIO_ALSEA,
        MES_ALSEA
    FROM
        SEGMENT_EVENTS.WOW_PROD_ANDROID.APPLICATION_INSTALLED
    INNER JOIN 
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    ON
        to_date(TIMESTAMP) = FECHA
    WHERE
        ANIO_ALSEA = 2023
),

INSTALLED_APP_IOS AS (
    SELECT
        ANIO_ALSEA,
        MES_ALSEA
    FROM
        SEGMENT_EVENTS.WOW_PROD_IOS.APPLICATION_INSTALLED
    INNER JOIN 
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME
    ON
        to_date(TIMESTAMP) = FECHA
    WHERE
        ANIO_ALSEA = 2023
),

INSTALLED_APP_TOTAL AS (
    SELECT * FROM INSTALLED_APP_IOS
    UNION ALL
    SELECT * FROM INSTALLED_APP_ANDROID
)

SELECT
    ANIO_ALSEA,
    MES_ALSEA,
    count(*) AS INSTALACIONES_DE_APP
FROM
    INSTALLED_APP_TOTAL
GROUP BY
    ANIO_ALSEA,
    MES_ALSEA
ORDER BY
    ANIO_ALSEA DESC,
    MES_ALSEA DESC