-- Ian Pineda
-- 23/06/05

WITH

FOLIOS_ENVIADOS AS (
    SELECT
        FOLIO_CUPON,
        USER_ID,
        to_date(max(TIMESTAMP)) AS FECHA
    FROM
        SEGMENT_EVENTS.HTTP_REGISTRA_CUPON.COUPON_RECORD AS ENVIADOS
    WHERE
        CAMPAINGID = '7K0VR'
    GROUP BY
        FOLIO_CUPON,
        USER_ID
),

ENVIADOS AS (
    SELECT
        SEM_ALSEA,
        ANIO_ALSEA,
        FOLIOS_ENVIADOS.*
    FROM
        FOLIOS_ENVIADOS
    INNER JOIN
        WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_DIM_TIME AS TIME
    USING(
        FECHA
    )
)

SELECT
    ANIO_ALSEA,
    SEM_ALSEA,
    count(ENVIADOS.FOLIO_CUPON) AS CUPONES_ENVIADOS,
    count(REDIMIDOS.MONTO_VENTA) AS REDENCIONES,
    REDENCIONES / CUPONES_ENVIADOS AS REDEMPTION_RATE,
    sum(REDIMIDOS.MONTO_VENTA) AS VENTA_CON_REDENCION
FROM
    ENVIADOS
LEFT JOIN
    SEGMENT_EVENTS.CUPONERA_ALSEA_PROD.REDEMPTION_COUPON AS REDIMIDOS
ON
    ENVIADOS.FOLIO_CUPON = REDIMIDOS.ID_COUPON
WHERE
    SEM_ALSEA IN (22, 23, 24)
GROUP BY
    ANIO_ALSEA,
    SEM_ALSEA
ORDER BY
    SEM_ALSEA DESC
;