WITH

RANGO_DE_FECHAS AS (
    SELECT
        to_date('2023-07-30') AS FECHA_FIN,
        FECHA_FIN - 180 AS FECHA_INICIO
)

SELECT 
    sum(VENTAS) AS VENTA,
    CASE
        WHEN FUENTE = 'TDL' THEN FUENTE
        ELSE 'WOW'
    END AS CANAL,
    ratio_to_report(VENTA) OVER () PORCENTAJE_DE_VENTA
FROM
    WOW_REWARDS.WORK_SPACE_WOW_REWARDS.DS_VENTAS_ORDENES_WOW
INNER JOIN
    RANGO_DE_FECHAS
ON
    to_date(DATETIME) <= FECHA_FIN
AND
    FECHA_INICIO < to_date(DATETIME)
WHERE
    POS_EMPLOYEE_ID NOT IN ('Power', '1 service cloud')
AND
    MARCA = 'VIPS MEXICO'
GROUP BY
    CANAL