WITH

TRANSACCIONES_OLO AS (
    SELECT DISTINCT
        to_date(MXP.ORDERDATE) AS FECHA,
        OLO.ORDERFINALPRICE / 1.16 AS VENTA,
        LOCATION_CODE AS CECO
    FROM
       "SEGMENT_EVENTS"."DOMINOS_OLO"."MXPOWERSALESLOG" MXP
    INNER JOIN 
        "SEGMENT_EVENTS"."DOMINOS_OLO"."DPMSALES_FULL" OLO
    ON 
        OLO.ORDER_NUMBER = MXP.ORDERNUMBER AND OLO.LOCATION_CODE = MXP.STORENUMBER 
    AND 
        TO_CHAR(OLO.ORDER_DATE,'YYYY-MM-DD') = MXP.ORDERDATE
    WHERE 
        OLO.ORDER_STATUS_CODE = 4
    AND 
        OLO.LOCATION_CODE NOT IN ('13001' , '13006', '13021', '11000')
    AND 
        UPPER(OLO.SOURCE_CODE) IN ('ANDROID' , 'DESKTOP', 'IOS', 'MOBILE', 'WEB', 'ANDROID2', 'DESKTOP2', 'IOSAPP', 'MOBILE2', 'WHATSAPP')
),

TRANSACCIONES_CLOUD AS (
    SELECT DISTINCT 
        to_date(SUBSTRING(STOREORDERID,1,10)) AS FECHA,
        PAYMENTSAMOUNT / 1.16 AS VENTA,
        STOREID AS CECO
    FROM 
        "SEGMENT_EVENTS"."DOMINOS_GOLO"."VENTA_CLOUD"
    WHERE 
        STOREID NOT LIKE '9%'
    AND 
        SOURCEORGANIZATIONURI IN ('order.dominos.com','resp-order.dominos.com','iphone.dominos.mx','android.dominos.mx') 
    AND 
        SOURCEORGANIZATIONURI IS NOT NULL
),

TRANSACCIONES_OLO_Y_CLOUD AS (
    SELECT
        CECO,
        SUM(VENTA) AS VENTAS 
    FROM
    (
        SELECT * FROM TRANSACCIONES_OLO
        UNION ALL
        SELECT * FROM TRANSACCIONES_CLOUD
    )
    WHERE
        FECHA >= to_date('2023-01-02')
    GROUP BY
        CECO
),

VENTAS_TOTALES AS (
    SELECT                          
        TOT.TIENDA AS CECO,
        SUM(TOT.VENTAS) VENTAS_TOTALES
    FROM 
        "WOW_REWARDS"."WORK_SPACE_WOW_REWARDS"."DATOS_TOTAL_ALSEA" TOT
    INNER JOIN 
        "WOW_REWARDS"."WORK_SPACE_WOW_REWARDS"."DS_DIM_TIME" T
    ON 
        T.FECHA = TO_CHAR(TO_DATE(TOT.FECHA,'DD/MM/YYYY'),'YYYY-MM-DD')
    AND 
        TO_DATE(TOT.FECHA,'DD/MM/YYYY') >= to_date('2023-01-02')
    GROUP BY 
        TOT.TIENDA
),

TIENDAS_CON_MAS_DE_UN_ANIO AS (
    SELECT                          
        TOT.TIENDA AS CECO
    FROM 
        "WOW_REWARDS"."WORK_SPACE_WOW_REWARDS"."DATOS_TOTAL_ALSEA" TOT
    GROUP BY 
        TOT.TIENDA
    HAVING
        current_date() - min(TO_DATE(TOT.FECHA,'DD/MM/YYYY')) > 365
)

SELECT
    CECO,
    TIENDA,
    sum(VENTAS) AS VENTA,
    sum(VENTAS_TOTALES) AS VENTA_TOTAL,
    VENTA / VENTA_TOTAL AS TENDER
FROM
    TRANSACCIONES_OLO_Y_CLOUD
INNER JOIN
    VENTAS_TOTALES
USING(
    CECO
)
INNER JOIN
    TIENDAS_CON_MAS_DE_UN_ANIO
USING(
    CECO
)
INNER JOIN
    ANALYTICS_HUB.DATA_HUB.DS_SUCURSALES_DP
USING(
    CECO
)
GROUP BY
    CECO,
    TIENDA
ORDER BY
    TENDER DESC

;
-- 11622 Pueblo Santa Fe (2)
-- 12342 Grand Plaza Ecatepec (37)
-- 11776 Corregidora (381)

SELECT * FROM ANALYTICS_HUB.DATA_HUB.DS_SUCURSALES_DP;